USE [BDHOTEL]
GO

/****** Object: Table [dbo].[FUNCIONARIOS] Script Date: 02/12/2021 17:56:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FUNCIONARIOS] (
    [USUÁRIO] NVARCHAR (50) NOT NULL,
    [SENHA]   NVARCHAR (50) NOT NULL
);


